module.exports = {
  '/api/v1/answers': {
    get: {
      tags: ['answers'],
      summary: '해당 날짜 데이터',
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'date',
          in: 'query',
          type: 'string',
          description: '원하는 일(2020-01-01)',
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              id: 88,
              userId: 121,
              missionId: 1,
              fileId: 3,
              imageUrl: null,
              content: '335',
              date: '2020-02-28',
              setDate: '2020-02-27',
              createdAt: '2020-02-28 00:08:15',
              updatedAt: '2020-02-28 00:08:15',
              mission: {
                id: 1,
                title: '좋아하는 디저트가 있나요?',
                isContent: true,
                isImage: true,
                cycle: 3,
                createdAt: '2020-01-12 20:54:34',
                updatedAt: '2020-01-12 20:54:34',
              },
              file: {
                id: 3,
                cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                part: 3,
                createdAt: '2020-01-27 18:05:56',
                updatedAt: '2020-01-27 18:05:56',
              },
            },
          },
        },
      },
    },
    post: {
      tags: ['answers'],
      summary: '답 작성',
      consumes: ['multipart/form-data'],
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'file',
          in: 'formData',
          description: 'file to upload',
          required: false,
          type: 'file',
        },
        {
          name: 'missionId',
          in: 'formData',
          description: 'file to upload',
          required: true,
          type: 'integer',
        },
        {
          name: 'content',
          in: 'formData',
          description: 'file to upload',
          required: false,
          type: 'string',
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 201,
              message: '',
              data: {
                id: 88,
                userId: 121,
                missionId: 1,
                fileId: 3,
                imageUrl: null,
                content: '335',
                date: '2020-02-28',
                setDate: '2020-02-27',
                createdAt: '2020-02-28 00:08:15',
                updatedAt: '2020-02-28 00:08:15',
                mission: {
                  id: 1,
                  title: '좋아하는 디저트가 있나요?',
                  isContent: true,
                  isImage: true,
                  cycle: 3,
                  createdAt: '2020-01-12 20:54:34',
                  updatedAt: '2020-01-12 20:54:34',
                },
                file: {
                  id: 3,
                  cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                  part: 3,
                  createdAt: '2020-01-27 18:05:56',
                  updatedAt: '2020-01-27 18:05:56',
                },
              },
            },
          },
        },
        404: {
          schema: {
            type: 'object',
            example: {
              status: 404,
              message: '해당날짜에 답변이 존재합니다.',
              data: null,
            },
          },
        },
      },
    },
  },
  '/api/v1/answers/{id}': {
    get: {
      tags: ['answers'],
      summary: '답 id로 조회',
      consumes: ['multipart/form-data'],
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'id',
          in: 'path',
          type: 'integer',
          default: 1,
          description: '답 ID',
          required: true,
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 200,
              message: '',
              data: {
                id: 88,
                userId: 121,
                missionId: 1,
                fileId: 3,
                imageUrl: null,
                content: '335',
                date: '2020-02-28',
                setDate: '2020-02-27',
                createdAt: '2020-02-28 00:08:15',
                updatedAt: '2020-02-28 00:08:15',
                mission: {
                  id: 1,
                  title: '좋아하는 디저트가 있나요?',
                  isContent: true,
                  isImage: true,
                  cycle: 3,
                  createdAt: '2020-01-12 20:54:34',
                  updatedAt: '2020-01-12 20:54:34',
                },
                file: {
                  id: 3,
                  cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                  part: 3,
                  createdAt: '2020-01-27 18:05:56',
                  updatedAt: '2020-01-27 18:05:56',
                },
              },
            },
          },
        },
      },
    },
    put: {
      tags: ['answers'],
      summary: '답 수정',
      consumes: ['multipart/form-data'],
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'id',
          in: 'path',
          type: 'integer',
          default: 1,
          description: '답 ID',
          required: true,
        },
        {
          name: 'file',
          in: 'formData',
          description: 'file to upload',
          required: false,
          type: 'file',
        },
        {
          name: 'content',
          in: 'formData',
          description: 'file to upload',
          required: false,
          type: 'string',
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 200,
              message: '',
              data: {
                id: 88,
                userId: 121,
                missionId: 1,
                fileId: 3,
                imageUrl: null,
                content: '335',
                date: '2020-02-28',
                setDate: '2020-02-27',
                createdAt: '2020-02-28 00:08:15',
                updatedAt: '2020-02-28 00:08:15',
                mission: {
                  id: 1,
                  title: '좋아하는 디저트가 있나요?',
                  isContent: true,
                  isImage: true,
                  cycle: 3,
                  createdAt: '2020-01-12 20:54:34',
                  updatedAt: '2020-01-12 20:54:34',
                },
                file: {
                  id: 3,
                  cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                  part: 3,
                  createdAt: '2020-01-27 18:05:56',
                  updatedAt: '2020-01-27 18:05:56',
                },
              },
            },
          },
        },
      },
    },
    delete: {
      tags: ['answers'],
      summary: '답 삭제',
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'id',
          in: 'path',
          type: 'integer',
          default: 1,
          description: '답 ID',
          required: true,
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 204,
              message: '답변을 삭제 했습니다.',
              data: null,
            },
          },
        },
      },
    },
  },
  '/api/v1/answers/week': {
    get: {
      tags: ['answers'],
      summary: '일주일치 데이터',
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 200,
              message: '',
              data: {
                status: 200,
                message: '',
                data: {
                  today: '2020-02-28',
                  answers: [
                    {
                      id: 40,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 87,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 88,
                      userId: 121,
                      missionId: 1,
                      fileId: 3,
                      imageUrl: null,
                      content: '335',
                      date: '2020-02-28',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-28 00:08:15',
                      updatedAt: '2020-02-28 00:08:15',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 3,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                        part: 3,
                        createdAt: '2020-01-27 18:05:56',
                        updatedAt: '2020-01-27 18:05:56',
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    },
  },
  '/api/v1/answers/list': {
    get: {
      tags: ['answers'],
      summary: '일주일치 데이터',
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 200,
              message: '',
              data: {
                status: 200,
                message: '',
                data: {
                  today: '2020-02-28',
                  answers: [
                    {
                      id: 40,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 87,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 88,
                      userId: 121,
                      missionId: 1,
                      fileId: 3,
                      imageUrl: null,
                      content: '335',
                      date: '2020-02-28',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-28 00:08:15',
                      updatedAt: '2020-02-28 00:08:15',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 3,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/J9smJXN7.pdf',
                        part: 3,
                        createdAt: '2020-01-27 18:05:56',
                        updatedAt: '2020-01-27 18:05:56',
                      },
                    },
                  ],
                },
              },
            },
          },
        },
      },
    },
  },
  '/api/v1/answers/month': {
    get: {
      tags: ['answers'],
      summary: '한달치 데이터',
      produces: ['application/json'],
      parameters: [
        {
          name: 'Authorization',
          in: 'header',
          type: 'string',
          description: 'API 인증 키',
          default:
            'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJiaXJ0aGRheSI6IjE5OTctMDEtMTYiLCJlbWFpbCI6Inl1Y2hvY29waWVAZ21haWwuY29tIiwibmFtZSI6IuycoOyglSIsImdlbmRlciI6IuyXrCIsInJlZnJlc2hEYXRlIjpudWxsLCJyZWZyZXNoVG9rZW4iOm51bGwsIm1pc3Npb24iOm51bGwsInNuc0lkIjoiMSIsInNuc1R5cGUiOiJnb29nbGUiLCJjcmVhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTAxLTAzVDE3OjM0OjM3LjAwMFoifSwiaWF0IjoxNTc4MDcyODc5LCJleHAiOjE1Nzg2Nzc2Nzl9.4jBy8Wrj9IukT2H2OU0UdqQjehNXMGio1KAd01z3DvE',
          required: true,
        },
        {
          name: 'date',
          in: 'query',
          type: 'string',
          description: '원하는 달(2020-01-01)',
        },
      ],
      responses: {
        200: {
          schema: {
            type: 'object',
            example: {
              status: 200,
              message: '',
              data: {
                date: '2020-02-01',
                monthAnswer: [
                  [
                    {
                      id: 40,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 87,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-27',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                  ],
                  [
                    {
                      id: 50,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-22',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                    {
                      id: 70,
                      userId: 121,
                      missionId: 1,
                      fileId: 7,
                      imageUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/LZZnJefh.jpeg',
                      content: '2134',
                      date: '2020-02-27',
                      setDate: '2020-02-22',
                      createdAt: '2020-02-27 23:22:14',
                      updatedAt: '2020-02-27 23:22:14',
                      mission: {
                        id: 1,
                        title: '좋아하는 디저트가 있나요?',
                        isContent: true,
                        isImage: true,
                        cycle: 3,
                        createdAt: '2020-01-12 20:54:34',
                        updatedAt: '2020-01-12 20:54:34',
                      },
                      file: {
                        id: 7,
                        cardUrl: 'https://yuchocopie.s3.ap-northeast-2.amazonaws.com/710Cz1v5.pdf',
                        part: 1,
                        createdAt: '2020-01-27 18:07:22',
                        updatedAt: '2020-01-27 18:07:22',
                      },
                    },
                  ],
                ],
              },
            },
          },
        },
      },
    },
  },
};
